topicname: Pokemon_Anaysis
title: Building software notification
base_url: http://pokeapi.co/api/v2
param_type: type
ntfy_topic: "notification_pokenmon_data"
plot_color: "skyblue"
plot_title: "Pokemon Analysis"
plot_x_axis_title: "Pokemon Types"
plot_y_axis_title: "Count"
figure_size: (10, 6)
default_save_path: "Pokemon_Analysis.pdf"
